### ISSUE TITLE
Python-ucto installation error on Google Colab

### ISSUE THREAD

**Issue by trister95** [proycon/python-ucto#17]
This morning I tried to install python-ucto on Colab by running:

`` !pip install python-ucto ``

Unfortunately, I got this error: 

```
Building wheels for collected packages: python-ucto
  error: subprocess-exited-with-error
  
  × Building wheel for python-ucto (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Building wheel for python-ucto (pyproject.toml) ... error
  ERROR: Failed building wheel for python-ucto
Failed to build python-ucto
ERROR: Could not build wheels for python-ucto, which is required to install pyproject.toml-based projects
```

With version 0.6.4 this worked fine, so I'm guessing there is a problem with version 0.6.5. Also, in my own python environment I had no problems installing the new version. 

Hope this can be fixed! :)

**Comment by proycon** [comment]
Oops, it seems I didn't properly upload some of the wheels (most notably Python 3.8 and Python 3.9), that probably caused this. Should be fixed now.
