### ISSUE TITLE
TokenRole has no attribute ENDOFQUOTE

### ISSUE THREAD

**Issue by emanjavacas** [proycon/python-ucto#4]
Hi there,
I noticed that `isendofquote` seems to be broken.

Seems like a typo on this line:

https://github.com/proycon/python-ucto/blob/65a7f03a92f60fa28e330a5fb735d75230cdbec4/ucto_wrapper.pyx#L29

which should be rather `ENDOFQUOTE`.

**Comment by proycon** [comment]
Right! Well spotted, will fix. Thanks!  (quote detection is fortunately disabled by default though)
