### ISSUE TITLE
Tokenizer does not return lowercase tokens when lowercase = True

### ISSUE THREAD

**Issue by martijnbentum** [proycon/python-ucto#8]
When I call tokenizer with lowercase True, the output contains tokens with uppercase.

t = ucto.Tokenizer("tokconfig-nld",lowercase = True,sentencedetection=False,paragraphdetection=False)                          
ucto: textcat configured from: /vol/customopt/lamachine.stable/share/ucto/textcat.cfg

z = x.article_set.all()[0]                                                                                                     

t.process(z.text)                                                                                                              

[str(token) for token in t]                                                                                                    

["'",
 'oor',
 'onze',
 'redacteur',
 'mr.',
 'F.',
 'KUITENBROUWER',
 'AMSTERDAM',

**Comment by proycon** [comment]
That indeed looks like a clear bug. I'll investigate!

**Comment by proycon** [comment]
This should be fixed now in v0.5.2 !

**Comment by martijnbentum** [comment]
thanks
